Week16/Monday/django-meetup/meetup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user_auth.urls')),
    path('meet/', include('meetup_app.urls'))
]

Week16/Monday/django-meetup/meetup_app/urls.py
from django.urls import path
from . import views

app_name = 'meet'

urlpatterns = [
#   -----Groups-----
    path('groups/', views.all_groups, name='all_groups'),
    path('new_group/', views.AddGroupView.as_view(), name='add_group'),
    path('<int:group_id>/', views.GroupDetailView.as_view(), name='group_details'),
    path('<pk>/update/', views.GroupUpdateView.as_view(), name='update_group'),
    path('<pk>/delete/', views.GroupDeleteView.as_view(), name='delete_group'),

#   -----Events-----
    path('<int:group_id>/add_event/', views.AddEventView.as_view(), name='add_event'),
    path('<int:group_id>/<int:event_id>/edit_event', views.EditEventView.as_view(), name='edit_event'),
    path('<int:group_id>/<int:event_id>/delete_event', views.DeleteEventView.as_view(), name='delete_event'),
]

Week16/Monday/django-meetup/user_auth/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'auth'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='user_auth/login.html'), name='login_user'),
    path('signup/', views.UserSignup.as_view(), name='user_signup'),
    path('logout/', views.CustomLogoutView.as_view(), name='user_logout')
]

Week16/Monday/django-meetup/meetup_app/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Group(models.Model):
    title = models.CharField(max_length=100)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='owner')
    users = models.ManyToManyField(get_user_model())
    description = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.title

class Event(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='events')
    date = models.DateTimeField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    image_url = models.URLField(null=True)

    def __str__(self) -> str:
        return self.title

Week16/Monday/django-meetup/user_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    test = models.BooleanField(default=False)

Week16/Monday/django-meetup/user_auth/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model


class UserAuthenticationForm(AuthenticationForm):
    pass

class UserSignupForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'test']

Week16/Monday/django-meetup/meetup_app/views.py
from django.urls import reverse
from django.shortcuts import render
from .models import  Group, Event
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth import get_user_model

User = get_user_model()

def all_groups(request):
    groups = Group.objects.all()
    return render(request, 'meetup_app/all_groups.html', {'groups': groups})

class GroupDetailView(DetailView):
    model = Group
    template_name = 'meetup_app/group_details.html'
    context_object_name='group'
    pk_url_kwarg = 'group_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['members'] = context['object'].users.all()
        context['events'] = context['object'].events.all()
        return context

def get_user(username):
    return User.objects.get(username=username)

class AddGroupView(CreateView):
    model = Group
    fields = ['title','users', 'description']
    success_url = '/meet/groups/'

    def form_valid(self, form):
        owner_username = self.request.user
        self.object = form.save(commit=False)
        self.object.owner = get_user(owner_username)
        print(self.object)
        self.object.save()
        return super().form_valid(form)

class GroupUpdateView(UpdateView):
    model = Group
    fields = '__all__'
    success_url = '/meet/groups/'

class GroupDeleteView(DeleteView):
    model = Group
    success_url = '/meet/groups/'

def get_group(group_id):
    return Group.objects.get(id=group_id)

class AddEventView(CreateView):
    model = Event
    fields = ['date', 'title', 'description', 'image_url']
    pk_url_kwarg = 'group_id'

    def form_valid(self, form):
        url_kwargs = self.kwargs
        self.object = form.save(commit=False)
        self.object.group = get_group(url_kwargs['group_id'])
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        url_kwargs = self.kwargs
        return reverse('meet:group_details', args=(url_kwargs['group_id'],) )

class EditEventView(UpdateView):
    model = Event
    fields = ['date', 'title', 'description', 'image_url']
    pk_url_kwarg = 'event_id'

    def form_valid(self, form):
        url_kwargs = self.kwargs
        self.object = form.save(commit=False)
        self.object.group = get_group(url_kwargs['group_id'])
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        url_kwargs = self.kwargs
        return reverse('meet:group_details', args=(url_kwargs['group_id'],) )

class DeleteEventView(DeleteView):
    model = Event
    pk_url_kwarg = 'event_id'

    def get_success_url(self) -> str:
        url_kwargs = self.kwargs
        return reverse('meet:group_details', args=(url_kwargs['group_id'],) )

Week16/Monday/django-meetup/user_auth/views.py
from .forms import UserSignupForm
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import get_user_model
# from django.contrib.auth.forms import UserCreationForm

class UserSignup(CreateView):
    model = get_user_model()
    form_class = UserSignupForm
    template_name = 'user_auth/signup.html'
    success_url = '/auth/'

class CustomLogoutView(LogoutView):
    next_page = '/auth/'

Week16/Monday/django-meetup/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Meetup{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="">
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Meetup</a>
        </div>
        
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'auth:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          {% else %}
            <li><a href="{% url 'auth:user_signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="{% url 'auth:login_user' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>



    <main>
      {% block content %}
      {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="" async defer></script>
  </body>
</html>